'use client';
import styled from 'styled-components';

interface RootProps {
	className?: string;
	children: React.ReactNode;
	title?: string;
	description?: string;
}

const RootLayout = ({ className, children, title = 'Next App', description = 'Generated by create next app' }: RootProps) => {
	return (
		<html
			lang="en"
			className={className}
		>
			<head>
				<title>{title}</title>
				<meta
					name="description"
					content={description}
				/>
			</head>
			<body>{children}</body>
		</html>
	);
};

const Root = styled(RootLayout)`
	margin: 0;
	background: linear-gradient(0deg, rgba(199, 199, 199, 1) 0%, rgba(255, 255, 255, 1) 50%);
	background-size: 100% 100vh;
`;

export default Root;
