'use client';
import styled from 'styled-components';
import GlobalStyles from '@/styles/GlobalStyles';
import Header from '../shell/I-Header';
interface RootProps {
	className?: string;
	children: React.ReactNode;
	title?: string;
	description?: string;
}

const RootLayout = ({ className, children, title = 'QuikSuite', description = 'Generated by create next app' }: RootProps) => {
	return (
		<>
			<html
				lang="en"
				className={className}
			>
				<head>
					<title>{title}</title>
					<meta
						name="description"
						content={description}
					/>
				</head>
				<GlobalStyles />
				<body>
					<Header />
					{children}
				</body>
			</html>
		</>
	);
};

const Root = styled(RootLayout)`
	:root {
		--header-background: pink;
	}
	background: linear-gradient(0deg, rgba(199, 199, 199, 1) 0%, rgba(255, 255, 255, 1) 50%);
	background-size: 100% 100vh;

	& body {
		margin: 0;
	}
`;

export default Root;
